// <auto-generated />
using System;
using AirportManagement.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirportManagement.Data.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirportManagement.Data.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocationId");

                    b.Property<int?>("WeatherId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("WeatherId");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            LocationId = -1
                        },
                        new
                        {
                            Id = -2,
                            LocationId = -2
                        },
                        new
                        {
                            Id = -3,
                            LocationId = -3
                        },
                        new
                        {
                            Id = -4,
                            LocationId = -4
                        },
                        new
                        {
                            Id = -5,
                            LocationId = -5
                        },
                        new
                        {
                            Id = -6,
                            LocationId = -6
                        },
                        new
                        {
                            Id = -7,
                            LocationId = -7
                        });
                });

            modelBuilder.Entity("AirportManagement.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocalTimeZoneName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Florence"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Elabuga"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Gatwick"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Innsbruk"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Bucharest"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Buchara"
                        });
                });

            modelBuilder.Entity("AirportManagement.Data.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("AirportManagement.Data.Airport", b =>
                {
                    b.HasOne("AirportManagement.Data.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AirportManagement.Data.Weather", "Weather")
                        .WithMany()
                        .HasForeignKey("WeatherId");
                });
#pragma warning restore 612, 618
        }
    }
}
